name: Check For Updates

on:
#  schedule:
#  - cron: "0 */2 * * *"    # Every 2 hours

  workflow_dispatch:
  
jobs:
  tag:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates.
        id: check
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.WF }}" \
          --request POST \
          -d '{"ref":"ref"}' \
          "https://api.github.com/repos/Zibri/VICE/actions/workflows/main.yaml/dispatches"
          
