name: Check For Updates

on:
  schedule:
  - cron: "*/30 * * * *"    # Every 2 hours

  workflow_dispatch:
  
jobs:
  tag:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates.
        id: check
        shell: bash
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          revision=$(svn info --show-item revision https://svn.code.sf.net/p/vice-emu/code/trunk/vice)
          curl -qs "https://github.com/Zibri/VICE/tags"|grep "class.*releases/tag/"|grep -q $revision && exit 0 || (
          echo okkkkkk
          exit1
          )
#            curl -X POST -d '{"ref":"main"}' -H "Accept: application/vnd.github.v3+json" \
#            -H "Authorization: token ${{ secrets.WF }} " \
#            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/main.yml/dispatches"
#          echo New revision ($revision) on SVN!
#          }
          
