name: Check For Updates

on:
#  schedule:
#  - cron: "0 */2 * * *"    # Every 2 hours

  workflow_dispatch:
  
jobs:
  tag:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates.
        id: check
        run: |
          set
          exit 1
          curl -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          --request POST \
          --data '{"event_type": "workflow_dispatch"}' \
          https://api.github.com/repos/$GITHUB_ACTOR/$(basename $GITHUB_WORKSPACE)/dispatches
          
