name: Check For Updates

on:
#  schedule:
#  - cron: "0 */2 * * *"    # Every 2 hours

  workflow_dispatch:

jobs:
  tag:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates.
        id: check
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
          --request POST \
          --data '{"event_type": "gooooooo!"}' \
          https://api.github.com/repos/${{ context.repo.repo }}/dispatches
      
